# Sun-$Revision: 30.8 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.
 
# Makefile for the Self primitives

ROOT         = ../../../..

FILES        = Makefile \
         asmPrims_gcc_ppc.s \
         asmPrims_mw_ppc.s \
         prim_table_arch_ppc.hh \
                        
         
include        ${ROOT}/templates/sources.make
