# Sun-$Revision: 10.3 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.

ROOT         = ../../..
FILES        = Makefile 
OBJECT_FILES = waste-empty.icon waste-empty_mask.icon \
               waste-full.icon  waste-full_mask.icon \
               pen.icon  pen_mask.icon \
               dot-pressed.icon dot-pressed_mask.icon dot.icon dot_mask.icon \
               line.icon line_mask.icon
include        ${ROOT}/templates/sources.make
