# Sun-$Revision: 14.1 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.
 
# Makefile for C preprocessor

ROOT         = ../../..
FILES        = Makefile
SELF_MODULES =       lexer           stages          tokens \
              grammarLexer    grammarStages   grammarTokens \
                    cLexer          cStages         cTokens \
                  cpp             cppStages       cppTokens
include        ${ROOT}/templates/sources.make
