# Sun-$Revision: 30.10 $
 
# Copyright 1994-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.

ROOT         = ../../..
FILES        = Makefile
SELF_MODULES = \
               allModulesModel \
               allOutliner \
	       allPluggableOutliner \
	       allSelfObjOutliner \
               browseMorphs \
	       changedModulesModel \
	       complexButtonMorph \
	       debuggerWidgets \
	       generalCategoryModel \
	       generalLeafModel \
	       generalModel \
	       generalSlotModel \
 	       larsText \
 	       moduleModel \
 	       moduleHolderModel \
	       moduleMorph \
               moduleWidgets \
               motifWidgets \
	       obsoleteOutliners \
	       obsObjOutliner \
               outliner \
	       outlinerPreferences \
	       outlinerWidgets \
	       pluggableAnnoStyle \
	       pluggableCommentStyle \
	       pluggableContentsStyle \
	       pluggableDebugger \
	       pluggableEditStyle \
	       pluggableLeafOutliner \
	       pluggableModuleWidgets \
	       pluggableOutliner \
	       pluggableSlicer \
	       pluggableSliceOut \
	       pluggableStyle \
	       pluggableTitleStyle \
	       powerOperations \
	       selfCatOrObjModel \
	       selfCategoryModel \
	       selfDebugger \
	       selfGenSlotModel \
	       selfModuleSetter \
	       selfObjectModel \
	       selfPCatModel \
	       selfPseudoSlotModel \
	       selfSliceCP \
	       selfSliceGroup \
	       selfSliceModel \
	       selfSlicer \
	       selfSlotModel \
	       sliceControlPanel \
	       sliceGroupModel \
	       sliceGroupOutliner \
	       sliceModel \
	       sliceReferrent \
	       slotModel \
	       structureEditing \
               syntaxErrorMorph \



include        ${ROOT}/templates/sources.make

