/* This information was generated by the primitive maker (primitiveMaker.self).
Please do not change it manually. -- dmu 12/91  */\
\
# ifdef INTERFACE_PRAGMAS
# pragma interface
# endif

/* Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.  */\
\
/* See the LICENSE file for license information.  */\
\
# define termcap_entries \
\
{ "tgetenv_wrapperprimGetenv", \
fntype(&tgetenv_wrapper_PrimGetenv__glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "tgetstr_wrappergetstr", \
fntype(&tgetstr_wrapper_Getstr__glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "tgoto_wrappergotoCol:Row:", \
fntype(&tgoto_wrapper_Goto_Col_Row__glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "tgetnumgetnum", \
fntype(&tgetnum_Getnum__glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "tgetflaggetflag", \
fntype(&tgetflag_Getflag__glue), \
ExternalPrimitive, \
BooleanPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \


/* This information was generated by the primitive maker (primitiveMaker.self).
Please do not change it manually. -- dmu 12/91  */\
\
# pragma interface

/* Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.  */\
\
/* See the LICENSE file for license information.  */\
\
# define termcap_glue    \
\
 C_func_1( string,, tgetenv_wrapper, tgetenv_wrapper_PrimGetenv__glue, fail, string,) \
 C_func_1( string,, tgetstr_wrapper, tgetstr_wrapper_Getstr__glue, fail, string,) \
 C_func_3( string,, tgoto_wrapper, tgoto_wrapper_Goto_Col_Row__glue, fail, string,, int,, int,) \
 C_func_1( int_or_errno,-1, tgetnum, tgetnum_Getnum__glue, , string,) \
 C_func_1( bool,, tgetflag, tgetflag_Getflag__glue, , string,) \


