/* This information was generated by the primitive maker (primitiveMaker.self).
Please do not change it manually. -- dmu 12/91  */\
\
# ifdef INTERFACE_PRAGMAS
# pragma interface
# endif

/* Copyright 1992-2012 AUTHORS.  */\
\
/* See the LICENSE file for license information.  */\
\
# define unix_entries \
\
{ "open_wrapbasicOpenFileNameFlags:Mode:ResultProxy:", \
fntype(&open_wrap_BasicOpenFileName_Flags_Mode__glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "socket_wrapbasicSocketDomainType:Protocol:ResultProxy:", \
fntype(&socket_wrap_BasicSocketDomain_Type_Protocol__glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "bind_wrapbasicBindSocketFamily:Port:Address:", \
fntype(&bind_wrap_BasicBindSocket_Family_Port_Address__glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "connect_wrapbasicConnectSocketFamily:Port:Address:", \
fntype(&connect_wrap_BasicConnectSocket_Family_Port_Address__glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "gethostbyaddr_wrapbasicGetHostByAddrType:", \
fntype(&gethostbyaddr_wrap_BasicGetHostByAddr_Type__glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "gethostbyname_wrapbasicGetHostByName", \
fntype(&gethostbyname_wrap_BasicGetHostByName__glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "listenbasicListenSocketBacklog:", \
fntype(&listen_BasicListenSocket_Backlog__glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "accept_wrapbasicAcceptSocketInfo:ResultProxy:", \
fntype(&accept_wrap_BasicAcceptSocket_Info__glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "fcntlbasicFcntlFileRequest:Arg:", \
fntype(&fcntl_BasicFcntlFile_Request_Arg__glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "close_wrapbasicCloseFile", \
fntype(&close_wrap_BasicCloseFile__glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "read_wrapbasicReadFileInto:Offset:Count:", \
fntype(&read_wrap_BasicReadFile_Into_Offset_Count__glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "write_wrapbasicWriteFileInto:Offset:Count:", \
fntype(&write_wrap_BasicWriteFile_Into_Offset_Count__glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "lseekbasicLseekFileOffset:Whence:", \
fntype(&lseek_BasicLseekFile_Offset_Whence__glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "select_wrapbasicSelectIntoSize:", \
fntype(&select_wrap_BasicSelectInto_Size__glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "select_read_wrapbasicSelectReadIntoSize:", \
fntype(&select_read_wrap_BasicSelectReadInto_Size__glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "unlinkbasicUnlink", \
fntype(&unlink_BasicUnlink__glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "getpid", \
fntype(&getpid_Getpid_glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "MYSELFsetFdResultProxy:", \
fntype(&MYSELF_SetFd__glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "MYSELFfileDescriptor", \
fntype(&MYSELF_FileDescriptor_glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "ExpandDir_primexpand", \
fntype(&ExpandDir_prim_Expand__glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "setsockoptLevel:OptName:OptVal:", \
fntype(&setsockopt_SetsockoptLevel_OptName_OptVal__glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "system_wrapcommand", \
fntype(&system_wrap_Command__glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "getenvenvironmentAt", \
fntype(&getenv_EnvironmentAt__glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "putenv_wrapenvironmentAtPut:", \
fntype(&putenv_wrap_EnvironmentAt_Put__glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "getcwd_wrapgetcwd", \
fntype(&getcwd_wrap_Getcwd_glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \


/* This information was generated by the primitive maker (primitiveMaker.self).
Please do not change it manually. -- dmu 12/91  */\
\
# pragma interface

/* Copyright 1992-2012 AUTHORS.  */\
\
/* See the LICENSE file for license information.  */\
\
# define unix_glue    \
\
 C_func_3( proxy_or_errno,(int,UnixFile_seal,-1), open_wrap, open_wrap_BasicOpenFileName_Flags_Mode__glue, , string,, int,, int,) \
 C_func_3( proxy_or_errno,(int,UnixFile_seal,-1), socket_wrap, socket_wrap_BasicSocketDomain_Type_Protocol__glue, , int,, int,, int,) \
 C_func_4( int_or_errno,-1, bind_wrap, bind_wrap_BasicBindSocket_Family_Port_Address__glue, fail, proxy_null,(int,UnixFile_seal), short,, unsigned_short,, cbv_len,char*) \
 C_func_4( int_or_errno,-1, connect_wrap, connect_wrap_BasicConnectSocket_Family_Port_Address__glue, fail, proxy_null,(int,UnixFile_seal), short,, unsigned_short,, cbv_len,char*) \
 C_func_2( string,, gethostbyaddr_wrap, gethostbyaddr_wrap_BasicGetHostByAddr_Type__glue, fail, cbv_len,char*, int,) \
 C_func_1( oop,, gethostbyname_wrap, gethostbyname_wrap_BasicGetHostByName__glue, fail, string,) \
 C_func_2( int_or_errno,-1, listen, listen_BasicListenSocket_Backlog__glue, , proxy_null,(int,UnixFile_seal), int,) \
 C_func_2( proxy_or_errno,(int,UnixFile_seal,-1), accept_wrap, accept_wrap_BasicAcceptSocket_Info__glue, , proxy_null,(int,UnixFile_seal), oop,objVector) \
 C_func_3( int_or_errno,-1, fcntl, fcntl_BasicFcntlFile_Request_Arg__glue, , proxy_null,(int,UnixFile_seal), int,, int,) \
 C_func_1( int_or_errno,-1, close_wrap, close_wrap_BasicCloseFile__glue, , proxy_null,(int,UnixFile_seal)) \
 C_func_4( int_or_errno,-1, read_wrap, read_wrap_BasicReadFile_Into_Offset_Count__glue, fail, proxy_null,(int,UnixFile_seal), bv_len,char*, int,, int,) \
 C_func_4( int_or_errno,-1, write_wrap, write_wrap_BasicWriteFile_Into_Offset_Count__glue, fail, proxy_null,(int,UnixFile_seal), cbv_len,char*, int,, int,) \
 C_func_3( int_or_errno,-1, lseek, lseek_BasicLseekFile_Offset_Whence__glue, , proxy_null,(int,UnixFile_seal), int,, int,) \
 C_func_2( int,, select_wrap, select_wrap_BasicSelectInto_Size__glue, fail, oop,objVector, int,) \
 C_func_2( int,, select_read_wrap, select_read_wrap_BasicSelectReadInto_Size__glue, fail, oop,objVector, int,) \
 C_func_1( int_or_errno,-1, unlink, unlink_BasicUnlink__glue, , string,) \
 C_func_0( int,, getpid, getpid_Getpid_glue, ) \
 C_func_1( proxy_null,(int,UnixFile_seal), MYSELF, MYSELF_SetFd__glue, , int,) \
 C_func_1( int,, MYSELF, MYSELF_FileDescriptor_glue, , proxy_null,(int,UnixFile_seal)) \
 C_func_1( string,, ExpandDir_prim, ExpandDir_prim_Expand__glue, fail, string,) \
 C_func_4( int_or_errno,-1, setsockopt, setsockopt_SetsockoptLevel_OptName_OptVal__glue, , proxy_null,(int,UnixFile_seal), int,, int,, cbv_len_null,char*) \
 C_func_1( int,, system_wrap, system_wrap_Command__glue, , string,) \
 C_func_1( string,, getenv, getenv_EnvironmentAt__glue, , string,) \
 C_func_2( int,, putenv_wrap, putenv_wrap_EnvironmentAt_Put__glue, , string,, string,) \
 C_func_0( string,, getcwd_wrap, getcwd_wrap_Getcwd_glue, fail) \


