/* This information was generated by the primitive maker (primitiveMaker.self).
Please do not change it manually. -- dmu 12/91  */\
\
# ifdef INTERFACE_PRAGMAS
# pragma interface
# endif
# undef PRIMITIVE_GLUE_FLAG_CODE
# define PRIMITIVE_GLUE_FLAG_CODE BlockGlueFlag gf(xlib_semaphore);
/* Copyright 1992-2026 AUTHORS.  */\
\
/* See the legal/LICENSE file for license information and legal/AUTHORS for authors.  */\
\
# define xft_entries \
\
/* xft  */\
\
{ "XftFontOpenNamexftFontOpenNameOnScreen:Name:ResultProxy:", \
fntype(&XftFontOpenName_XftFontOpenNameOnScreen_Name__glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
true, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
true, /* can walk stack         */ \
true, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XftDrawCreatexftDrawCreate:Visual:Colormap:ResultProxy:", \
fntype(&XftDrawCreate_XftDrawCreate_Visual_Colormap__glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
true, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
true, /* can walk stack         */ \
true, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XftTextExtents8_wrapxftTextExtents8:String:Extents:", \
fntype(&XftTextExtents8_wrap_XftTextExtents8_String_Extents__glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
true, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
true, /* can walk stack         */ \
true, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XftColorAllocValuexftColorAllocValue:Colormap:RenderColor:XftColor:", \
fntype(&XftColorAllocValue_XftColorAllocValue_Colormap_RenderColor_XftColor__glue), \
ExternalPrimitive, \
BooleanPrimType, \
true, /* can fail               */ \
true, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
true, /* can walk stack         */ \
true, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XftFont_newnewResultProxy", \
fntype(&XftFont_new_New_glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XftFont_deletedelete", \
fntype(&XftFont_delete_Delete_glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XftFont_ascentascent", \
fntype(&XftFont_ascent_Ascent_glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XGlyphInfo_newnewResultProxy", \
fntype(&XGlyphInfo_new_New_glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XGlyphInfo_deletedelete", \
fntype(&XGlyphInfo_delete_Delete_glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XGlyphInfo_widthwidth", \
fntype(&XGlyphInfo_width_Width_glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XGlyphInfo_heightheight", \
fntype(&XGlyphInfo_height_Height_glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XGlyphInfo_xx", \
fntype(&XGlyphInfo_x_X_glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XGlyphInfo_yy", \
fntype(&XGlyphInfo_y_Y_glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XGlyphInfo_xOffxOff", \
fntype(&XGlyphInfo_xOff_XOff_glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XGlyphInfo_yOffyOff", \
fntype(&XGlyphInfo_yOff_YOff_glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XRenderColor_newnewResultProxy", \
fntype(&XRenderColor_new_New_glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XRenderColor_deletedelete", \
fntype(&XRenderColor_delete_Delete_glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XRenderColor_redred", \
fntype(&XRenderColor_red_Red_glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XRenderColor_greengreen", \
fntype(&XRenderColor_green_Green_glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XRenderColor_blueblue", \
fntype(&XRenderColor_blue_Blue_glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XRenderColor_alphaalpha", \
fntype(&XRenderColor_alpha_Alpha_glue), \
ExternalPrimitive, \
IntegerPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XRenderColor_redred:", \
fntype(&XRenderColor_red_Red__glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XRenderColor_greengreen:", \
fntype(&XRenderColor_green_Green__glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XRenderColor_blueblue:", \
fntype(&XRenderColor_blue_Blue__glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XRenderColor_alphaalpha:", \
fntype(&XRenderColor_alpha_Alpha__glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XftColor_newnewResultProxy", \
fntype(&XftColor_new_New_glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XftColor_deletedelete", \
fntype(&XftColor_delete_Delete_glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
false, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
false, /* can walk stack         */ \
false, /* can abort process      */ \
"Generated by the primitive maker" },\
 \
{ "XftDrawString8_wrapxftDrawString8:Font:X:Y:String:", \
fntype(&XftDrawString8_wrap_XftDrawString8_Font_X_Y_String__glue), \
ExternalPrimitive, \
UnknownPrimType, \
true, /* can fail               */ \
true, /* can scavenge           */ \
false, /* can be constant folded */ \
true, /* cannot be moved or cut */ \
true, /* can walk stack         */ \
true, /* can abort process      */ \
"Generated by the primitive maker" },\
 \

# undef PRIMITIVE_GLUE_FLAG_CODE
# define PRIMITIVE_GLUE_FLAG_CODE


/* This information was generated by the primitive maker (primitiveMaker.self).
Please do not change it manually. -- dmu 12/91  */\
\
# ifdef INTERFACE_PRAGMAS
# pragma interface
# endif
# undef PRIMITIVE_GLUE_FLAG_CODE
# define PRIMITIVE_GLUE_FLAG_CODE BlockGlueFlag gf(xlib_semaphore);
/* Copyright 1992-2026 AUTHORS.  */\
\
/* See the legal/LICENSE file for license information and legal/AUTHORS for authors.  */\
\
# define xft_glue    \
\
/* xft  */\
\
 C_func_3( proxy,(XftFont*,XftFont_seal), XftFontOpenName, XftFontOpenName_XftFontOpenNameOnScreen_Name__glue, , proxy,(Display*,Display_seal), int,, string,) \
 C_func_4( proxy,(XftDraw*,XftDraw_seal), XftDrawCreate, XftDrawCreate_XftDrawCreate_Visual_Colormap__glue, , proxy,(Display*,Display_seal), proxy,(Drawable,ANY_SEAL), proxy,(Visual*,Visual_seal), proxy,(Colormap,Colormap_seal)) \
 C_func_4( void,, XftTextExtents8_wrap, XftTextExtents8_wrap_XftTextExtents8_String_Extents__glue, , proxy,(Display*,Display_seal), proxy,(XftFont*,XftFont_seal), string_len_null,, proxy,(XGlyphInfo*,XGlyphInfo_seal)) \
 C_func_5( bool,, XftColorAllocValue, XftColorAllocValue_XftColorAllocValue_Colormap_RenderColor_XftColor__glue, , proxy,(Display*,Display_seal), proxy,(Visual*,Visual_seal), proxy,(Colormap,Colormap_seal), proxy,(XRenderColor*,XRenderColor_seal), proxy,(XftColor*,XftColor_seal)) \
 CC_new_0( proxy,(XftFont*,XftFont_seal), XftFont, XftFont_new_New_glue) \
 CC_delete( proxy,(XftFont*,XftFont_seal), XftFont_delete_Delete_glue) \
 C_get_comp( int,, proxy,(XftFont*,XftFont_seal), .ascent, XftFont_ascent_Ascent_glue) \
 CC_new_0( proxy,(XGlyphInfo*,XGlyphInfo_seal), XGlyphInfo, XGlyphInfo_new_New_glue) \
 CC_delete( proxy,(XGlyphInfo*,XGlyphInfo_seal), XGlyphInfo_delete_Delete_glue) \
 C_get_comp( unsigned_short,, proxy,(XGlyphInfo*,XGlyphInfo_seal), .width, XGlyphInfo_width_Width_glue) \
 C_get_comp( unsigned_short,, proxy,(XGlyphInfo*,XGlyphInfo_seal), .height, XGlyphInfo_height_Height_glue) \
 C_get_comp( short,, proxy,(XGlyphInfo*,XGlyphInfo_seal), .x, XGlyphInfo_x_X_glue) \
 C_get_comp( short,, proxy,(XGlyphInfo*,XGlyphInfo_seal), .y, XGlyphInfo_y_Y_glue) \
 C_get_comp( short,, proxy,(XGlyphInfo*,XGlyphInfo_seal), .xOff, XGlyphInfo_xOff_XOff_glue) \
 C_get_comp( short,, proxy,(XGlyphInfo*,XGlyphInfo_seal), .yOff, XGlyphInfo_yOff_YOff_glue) \
 CC_new_0( proxy,(XRenderColor*,XRenderColor_seal), XRenderColor, XRenderColor_new_New_glue) \
 CC_delete( proxy,(XRenderColor*,XRenderColor_seal), XRenderColor_delete_Delete_glue) \
 C_get_comp( unsigned_short,, proxy,(XRenderColor*,XRenderColor_seal), .red, XRenderColor_red_Red_glue) \
 C_get_comp( unsigned_short,, proxy,(XRenderColor*,XRenderColor_seal), .green, XRenderColor_green_Green_glue) \
 C_get_comp( unsigned_short,, proxy,(XRenderColor*,XRenderColor_seal), .blue, XRenderColor_blue_Blue_glue) \
 C_get_comp( unsigned_short,, proxy,(XRenderColor*,XRenderColor_seal), .alpha, XRenderColor_alpha_Alpha_glue) \
 C_set_comp( proxy,(XRenderColor*,XRenderColor_seal), .red, unsigned_short,, XRenderColor_red_Red__glue) \
 C_set_comp( proxy,(XRenderColor*,XRenderColor_seal), .green, unsigned_short,, XRenderColor_green_Green__glue) \
 C_set_comp( proxy,(XRenderColor*,XRenderColor_seal), .blue, unsigned_short,, XRenderColor_blue_Blue__glue) \
 C_set_comp( proxy,(XRenderColor*,XRenderColor_seal), .alpha, unsigned_short,, XRenderColor_alpha_Alpha__glue) \
 CC_new_0( proxy,(XftColor*,XftColor_seal), XftColor, XftColor_new_New_glue) \
 CC_delete( proxy,(XftColor*,XftColor_seal), XftColor_delete_Delete_glue) \
 C_func_6( void,, XftDrawString8_wrap, XftDrawString8_wrap_XftDrawString8_Font_X_Y_String__glue, , proxy,(XftDraw*,XftDraw_seal), proxy,(XftColor*,XftColor_seal), proxy,(XftFont*,XftFont_seal), int,, int,, string_len_null,) \

# undef PRIMITIVE_GLUE_FLAG_CODE
# define PRIMITIVE_GLUE_FLAG_CODE


