#!/bin/bash

################################################
#
#   Build Linux VM
#
#
#   From:
#       Clean Ubuntu 9.04
#
#   Install:
#     csh
#     libc6-dev
#     g++
#     flex-old
#     build-essential
#     xorg-dev
#     libncurses5-dev
#
#   Do:

export SELF_WORKING_DIR=${PWD}/.. 
echo Setting paths: SELF_WORKING_DIR = $SELF_WORKING_DIR

export PATH=$PATH:$SELF_WORKING_DIR/bin/linux
export PATH=$PATH:$SELF_WORKING_DIR/bin/shell

echo Making support binaries...
cd $SELF_WORKING_DIR/bin/linux
make

echo Preparing...
cd $SELF_WORKING_DIR/vm/linux/generated
make lists

echo Build VM...
cd $SELF_WORKING_DIR/vm/linux/optimized
make

echo Stripping built VM for release...
strip $SELF_WORKING_DIR/vm/linux/optimized/Self

echo Copying VM to $SELF_WORKING_DIR/Self
cp $SELF_WORKING_DIR/vm/linux/optimized/Self $SELF_WORKING_DIR/Self




