#!/bin/bash

################################################
#
#   Build MacOS X VM
#
#	Move root of source tree to ~/self
#

export SELF_WORKING_DIR=${PWD}/.. 
echo Setting paths: SELF_WORKING_DIR = $SELF_WORKING_DIR

export PATH=$PATH:$SELF_WORKING_DIR/bin/mac_osx
export PATH=$PATH:$SELF_WORKING_DIR/bin/shell

export MAKE=/usr/bin/make

xcodebuild -project ../vm/mac_osx/vm_project/vm_project.xcodeproj -target Self



