# Sun-$Revision: 30.6 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.
 
ROOT         = ../../..
FILES        = Makefile
SELF_MODULES = quicksort sorttests
include        ${ROOT}/templates/sources.make
