# Sun-$Revision: 30.6 $
 
# Copyright 1994-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
ROOT         = ../../..
FILES        = Makefile
SELF_MODULES = quicksort sorttests
include        ${ROOT}/templates/sources.make
