# Sun-$Revision: 30.6 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.

ROOT         = ../..
FILES        = Makefile edglobals
SELF_MODULES = crypto example fixCopyDowns reorganizer programmingExamples
include        ${ROOT}/templates/sources.make
