# Sun-$Revision: 30.6 $
 
# Copyright 1994-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.

ROOT         = ../..
FILES        = Makefile edglobals
SELF_MODULES = crypto example fixCopyDowns reorganizer programmingExamples
include        ${ROOT}/templates/sources.make
