# Sun-$Revision: 30.6 $
 
# Copyright 1996-2006 Sun Microsystems, Inc.
# See the LICENSE file for license information.
 
# Makefile for Pep

ROOT         = ../../..
FILES        = Makefile PepTest.java
SELF_MODULES = pep                         \
	       pep_runtime                 \
               pep_extensions              \

include        ${ROOT}/templates/sources.make
