# Sun-$Revision: 30.7 $
 
# Copyright 1994-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.

ROOT         = ../..
FILES        = Makefile
SELF_MODULES = allGraphics \
	       bitmap \
	       bitmapShape \
	       colormap \
	       color \
	       colorRange \
	       cursor \
	       drawing \
	       eventWatcher \
	       eventHandler \
	       font \
	       fontSpec \
	       inBetweener \
	       macToolbox \
	       macToolboxEvts \
	       movingBitmap \
	       movingShape \
	       pattern \
	       spline \
	       window \
	       windoid \
	       xBitmapMaker \
	       xIconMaker \
	       xlib \
	       xPixmapMaker 

include        ${ROOT}/templates/sources.make
