
# Sun-$Revision: 30.9 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the Self runtime system

ROOT         = ../../../..
FILES        = Makefile \
               asmDefs_gcc_sparc.hh \
               runtime_asm_gcc_sparc.s \

C_MODULES    = \
               aCompiler_sparc \
               conversion_sparc \
               framePieces_sparc \
               frame_format_sparc \
               frame_iterator_sparc \
               frame_sparc \
               interruptedCtx_sparc \
               registerLocator_sparc \
               runtime_sparc \
               uncommonBranch_sparc \
               vframe_sparc \
               
         
include        ${ROOT}/templates/sources.make
