# Sun-$Revision: 30.7 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.
 
# Makefile for the Self parser and byte code generator

ROOT         = ../../../..
FILES        = Makefile

C_MODULES    = branchSet \
               byteCodes \
               expr \
               kinds \
               labelSet \
               list \
               parser \
               positionTable \
               preserve \
               scanner \
               send \
               slot \
               str \
               stringUtil
       
include        ${ROOT}/templates/sources.make
