# Sun-$Revision: 30.9 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the Self memory system

ROOT         = ../../../..
FILES        = Makefile enum_sparc.s search_sparc.hh search_sparc.cpp

         
include        ${ROOT}/templates/sources.make
