# Sun-$Revision: 30.8 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the Self memory system

ROOT         = ../../../..
FILES        = Makefile \
               search_ppc.hh \
               search_ppc.cpp

include        ${ROOT}/templates/sources.make
