# Sun-$Revision: 30.10 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.

ROOT         = ../..
FILES        = Makefile
OBJECT_FILES = factory.self
SELF_MODULES = allUI2 paint specialPaintManager \
               scalableFont canvas ui2Event activity morph worldMorph\
	       morphSaving \
               morphLib handMorph layoutMorphs frameMorphs userQueryMorph\
               simpleFrameMorph ui2Button ui2Menu pointerMorph\
	       pluggablePointerMorph\
               marqueeMorph metaMorph editorMorphs\
               buttonMorphs colorWorld histogramMorph\
               ui2Demo pixmapMorphs desktop carpetMorph arrowMorphs\
               widgetMorphs trashCanMorph animatedLayoutMorphs \
               radarView ui2ResultReporter ui2test morphFinder \
               coreSampler idealGas demoUtilities sunRasterFile \
	       propertySheets factoryMorph snapshotOptionsMorph \
               capability userProfile  \
               XILColormap smallComputer smallComputerProto \
	       macEvents xEvents \
               operandSelectors \
	       keyCaps keyCapCombos \
	       autoCompletion

DIRECTORIES  = icons outliner examples
include        ${ROOT}/templates/sources.make
