# Sun-$Revision: 1.2 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the Self native code zone manager

ROOT         = ../../../..
FILES        = Makefile \
               addrDesc_i386.hh \
               allocZone_i386.s \
               addrDesc_i386.cpp \
               countPattern_i386.cpp \
               countPattern_i386.hh \
               countStub_i386.cpp \
               countStub_i386.hh \
               nmethod_i386.hh \
               nmethod_i386.cpp \
               trapdoors_i386.hh \
               trapdoors_i386.cpp \


C_MODULES    = 
         
include        ${ROOT}/templates/sources.make
