# Sun-$Revision: 30.9 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.

ROOT         = ..
FILES        = Makefile
DIRECTORIES  = src templates svr4 mac_osx mac_project_builder


include        ${ROOT}/templates/sources.make


