# Sun-$Revision: 30.9 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.

ROOT         = ..
FILES        = Makefile
DIRECTORIES  = src templates svr4 mac_osx


include        ${ROOT}/templates/sources.make


