# Sun-$Revision: 30.7 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the Self lookup system

ROOT         = ../../../..
FILES        = Makefile \
               cacheStub_inline_sparc.hh

C_MODULES    = \
         cacheStub_sparc \
         diDesc_sparc \
         sendDesc_sparc \
         
include        ${ROOT}/templates/sources.make
