# Sun-$Revision: 30.8 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the Self assembler
ROOT         = ../../../..
FILES        = Makefile tag.hh

C_MODULES      = \
               assignmentMap \
               assignmentOop \
               blockMap \
               blockOop \
               byteVectorMap \
               byteVectorOop \
               codeLikeSlotsMap \
               codeSlotsMap \
               fctProxyMap \
               fctProxyOop \
               floatMap \
               floatOop \
               foreignMap \
               foreignOop \
               immediateMap \
               map \
               mapMap \
               mapOop \
               markMap \
               markOop \
               memOop \
               mirrorMap \
               mirrorOop \
               objVectorMap \
               objVectorOop \
               oop \
               oopsOop \
               processMap \
               processOop \
               profilerMap \
               profilerOop \
               proxyMap \
               proxyOop \
               slotDesc \
               slotType \
               slotsMap \
               slotsMapDeps \
               slotsOop \
               smiMap \
               smiOop \
               stringMap \
               stringOop \
               vframeMap \
               vframeOop \



include        ${ROOT}/templates/sources.make
