# Sun-$Revision: 30.5 $
 
# Copyright 1994-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.

ROOT         = ..
FILES        = Makefile LICENSE
SELF_MODULES = small medium all smallUI2 smallUI3D all2 release4_0
OBJECT_FILES = Snapshot
UPDATE_EXCL  = ${OBJECT_FILES}
DIRECTORIES  = core glue ui1 ui2 ui3D tests misc applications graphics
include        ${ROOT}/templates/sources.make
