# Sun-$Revision: 1.2 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the Self primitives

ROOT         = ../../../..

FILES        = Makefile \
         asmPrims_gcc_i386.s \
         prim_table_arch_i386.hh \
                        
         
include        ${ROOT}/templates/sources.make
