# Sun-$Revision: 30.7 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.
 
# Makefile for the fast Self compiler

ROOT         = ../../../..
FILES        = Makefile codeGen_inline_sparc.hh

C_MODULES    = \
         codeGen_sparc \
	 fcompiler_sparc \
         registerState_sparc \
         registerString_sparc \
         

include        ${ROOT}/templates/sources.make
