# Sun-$Revision: 30.8 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the Self primitives

ROOT         = ../../../..

FILES        = Makefile \
               include_glue_unix.hh \
               prim_table_os_unix.hh \
               x_includes.hh \
               
C_MODULES    = \
         unixPrims \
         unixPrims.glue \
         xlibPrims \
         
include        ${ROOT}/templates/sources.make
