
# Sun-$Revision: 30.9 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.
 
# Makefile for the Self runtime system

ROOT         = ../../../..
FILES        = Makefile \
               aCompiler_ppc.hh \
               aCompiler_ppc.cpp \
               asmDefs_gcc_ppc.hh \
               asmDefs_mw_ppc.hh \
               conversion_ppc.cpp \
               conversion_ppc.hh \
               framePieces_ppc.cpp \
               framePieces_ppc.hh \
               frame_format_ppc.cpp \
               frame_format_ppc.hh \
               frame_iterator_ppc.cpp \
               frame_iterator_ppc.hh \
               frame_ppc.cpp \
               frame_ppc.hh \
               interruptedCtx_ppc.cpp \
               interruptedCtx_ppc.hh \
               registerLocator_ppc.cpp \
               registerLocator_ppc.hh \
               runtime_asm_gcc_ppc.s \
               runtime_asm_mw_ppc.s \
               runtime_ppc.cpp \
               runtime_ppc.hh \
               stubs_ppc.cpp \
               uncommonBranch_ppc.cpp \
               vframe_ppc.cpp \
         
include        ${ROOT}/templates/sources.make

