# Sun-$Revision: 30.8 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.
 
# Makefile for the Self native code zone manager

ROOT         = ../../../..
FILES        = Makefile allocZone_sparc.s

C_MODULES    = addrDesc_sparc \
         countPattern_sparc \
         countStub_sparc \
         nmethod_sparc \
         trapdoors_sparc \
         
include        ${ROOT}/templates/sources.make
