# Sun-$Revision: 20.2 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.

ROOT         = ../..
FILES        = Makefile
SELF_MODULES = allUI3D doubleBuffering examples point3d \
	       simpleWindow transform triangle window3d
DIRECTORIES  = perlForXgl
include        ${ROOT}/templates/sources.make
