# Sun-$Revision: 30.7 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.
 
# Makefile for the Self assembler
ROOT         = ../../../..
FILES        = Makefile sparc.hh asm_inline_sparc.hh

C_MODULES    = asm_sparc \
         disasm_sparc \
         fields_sparc \
         opc_sparc \
         pinsn_sparc \
         regs_sparc \

include        ${ROOT}/templates/sources.make
