# Sun-$Revision: 30.7 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the Self assembler
ROOT         = ../../../..
FILES        = Makefile

C_MODULES    = asm \
         disasm \
         fields \
         label \
         nameDesc \
         pcDesc \
         regs \
         scopeDesc \

include        ${ROOT}/templates/sources.make
