
# Sun-$Revision: 1.2 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the Self runtime system

ROOT         = ../../../..
FILES        = Makefile \
               aCompiler_i386.hh \
               aCompiler_i386.cpp \
               asmDefs_gcc_i386.hh \
               conversion_i386.cpp \
               conversion_i386.hh \
               framePieces_i386.cpp \
               framePieces_i386.hh \
               frame_format_i386.cpp \
               frame_format_i386.hh \
               frame_iterator_i386.cpp \
               frame_iterator_i386.hh \
               frame_i386.cpp \
               frame_i386.hh \
               interruptedCtx_i386.cpp \
               interruptedCtx_i386.hh \
               registerLocator_i386.cpp \
               registerLocator_i386.hh \
               runtime_asm_gcc_i386.s \
               runtime_i386.cpp \
               runtime_i386.hh \
               stubs_i386.cpp \
               uncommonBranch_i386.cpp \
               vframe_i386.cpp \
         
include        ${ROOT}/templates/sources.make

