# Sun-$Revision: 30.7 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.
 
# Makefile for the Self assembler
ROOT         = ../../..
FILES        = Makefile

DIRECTORIES = \
        os \
        prims \
        runtime \

include        ${ROOT}/templates/sources.make
