# Sun-$Revision: 30.7 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the Self runtime system

ROOT         = ../../../..
FILES        = Makefile \
               config_unix.hh

C_MODULES    = \
               interruptedCtx_unix \
               machineCache_unix \
               monitorHooks_unix \
               monitorPieces_unix
         
include        ${ROOT}/templates/sources.make
