# Sun-$Revision: 30.7 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.
 
# Makefile for the Self svr4 debug directory

ROOT         = ../../..
FILES        = Makefile
AOUT         = Self
UPDATE_EXCL  = ${AOUT}


include        ${ROOT}/vm/templates/svr4.make
include        ${ROOT}/vm/templates/debug.make
include        ${ROOT}/templates/sources.make
include        ../generated/Dependencies
include        ${ROOT}/vm/templates/svr4_write.make
