# Sun-$Revision: 30.6 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.

ROOT         = ../..
FILES        = Makefile ui.icon
SELF_MODULES = allUI\
               enumResult slab uiColormap uiColorPalette boxSize boxBitmap\
               uiNester uiWorld boxBlueprint uiBody objectBody slotCpt\
               uiButton contentsButton slotNameCpt slotContentsCpt menu\
               menuItem hierarchicalMenu menuButton hiddenSlotsButton\
               objectButton slotButton sendButton objBodyTypes\
               animator ui arrowheadCache uiArrow textEditor\
               uiNotifier transcript diffUI toggleBody togglers uiDemo \
	       objBodyRegions
include        ${ROOT}/templates/sources.make
