# Sun-$Revision: 30.6 $
 
# Copyright 1996-2006 Sun Microsystems, Inc.
# See the LICENSE file for license information.
 
# Makefile for the Java server

ROOT         = ../../..
FILES        = Makefile
SELF_MODULES = loadJavaServer                \
	       javaInterface             

include        ${ROOT}/templates/sources.make
