# Sun-$Revision: 30.8 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the Self native code zone manager

ROOT         = ../../../..
FILES        = Makefile

C_MODULES    = \
  addrDesc \
  codeTable \
  countPattern \
  countStub \
  fprofiler \
  ncode \
  nmethod \
  nmethodScopes \
  nmln \
  scopeDescRecorder \
  trapdoors \
  zone \
  zoneHeap \

include        ${ROOT}/templates/sources.make
