# Sun-$Revision: 1.2 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the Self assembler
ROOT         = ../../../..
FILES        = Makefile \
               asm_inline_i386.hh \
               asm_i386.cpp \
               asm_i386.hh \
               disasm_i386.cpp \
               disasm_i386.hh \
               fields_i386.cpp \
               fields_i386.hh \
               regs_i386.cpp \
               regs_i386.hh \


include        ${ROOT}/templates/sources.make
