# Sun-$Revision: 30.8 $
 
# Copyright 1994-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.

ROOT         = ../..
FILES        = Makefile\
               sun4.make svr4.make sun4_write.make svr4_write.make \
               mac_osx.make \
               debug.make  optimized.make profiled.make\
               compile.make link.make
include        ${ROOT}/templates/sources.make
