# Sun-$Revision: 30.6 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.
 
# Makefile for Mango

ROOT         = ../../..
FILES        = Makefile Ansi-C.grm mangoTest.grm stGrammar.grm 
SELF_MODULES = genansi                 \
               gramBuild               \
               grammar                 \
               mango                   \
               mangoTest.behavior      \
               parsers                 \
               prodSet                 \
               ptokens                 \
               stGrammar               \
               treeBuilders            \
               typedefFilter           \
               stGrammar.behavior      \
	       Ansi-C.behavior

include        ${ROOT}/templates/sources.make
