# Sun-$Revision: 30.7 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the fast Self compiler

ROOT         = ../../../..
FILES        = Makefile

C_MODULES    = blist \
               codeGen \
               fcompiler \
               fscope \
               registerState \
               registerString 

include        ${ROOT}/templates/sources.make
