# Sun-$Revision: 30.7 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the Self lookup system

ROOT         = ../../../..
FILES        = Makefile

C_MODULES    = cacheStub \
               complexLookup \
               deps \
               diDesc \
               key \
               sendDesc \
               simpleLookup \
               slotRef \
               target
       
include        ${ROOT}/templates/sources.make
