# Sun-$Revision: 30.8 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the Self native code zone manager

ROOT         = ../../../..
FILES        = Makefile \
               addrDesc_ppc.hh \
               allocZone_ppc.s \
               addrDesc_ppc.cpp \
               countPattern_ppc.cpp \
               countPattern_ppc.hh \
               countStub_ppc.cpp \
               countStub_ppc.hh \
               nmethod_ppc.hh \
               nmethod_ppc.cpp \
               trapdoors_ppc.hh \
               trapdoors_ppc.cpp \


C_MODULES    = 
         
include        ${ROOT}/templates/sources.make
