#
# Sun-$Revision: 30.4 $ $UW-Revision$
#
# Makefile for the SIC Self compiler
#

ROOT         = ../../../..
FILES        = Makefile \
               genHelper.hh \
               

C_MODULES    = \
  aNode \
  basicBlock \
  bitVector \
  defUse \
  genHelper \
  inlining \
  longRegString \
  node \
  nodeGen \
  opcode \
  preg \
  regAlloc \
  rscope \
  sic \
  sicExpr \
  sicInline \
  sicPrimline \
  sicScope \
  sicSplit \
  slist \
  tracing 
         
include        ${ROOT}/templates/sources.make
