# Sun-$Revision: 14.1 $
 
# Copyright 1994 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.

ROOT         = ../../..
FILES        = Makefile
SELF_MODULES = pixelGridMorph
include        ${ROOT}/templates/sources.make

