# Sun-$Revision: 14.1 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.

ROOT         = ../../..
FILES        = Makefile
SELF_MODULES = pixelGridMorph
include        ${ROOT}/templates/sources.make

