# Sun-$Revision: 1.2 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the Self memory system

ROOT         = ../../../..
FILES        = Makefile \
               search_i386.hh \
               search_i386.cpp

include        ${ROOT}/templates/sources.make
