
# Sun-$Revision: 30.7 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the Self runtime system

ROOT         = ../../../..

FILES = \
  Makefile \
  asmDefs.hh \
  asserts.hh \
  bits.hh \
  config.hh \
  error.hh \
  macros.hh \
  top.hh \
  top_includes.hh \
  types.hh

C_MODULES =  \
  aCompiler \
  allocation \
  asyncMalloc \
  callgraph \
  clist \
  conversion \
  debug \
  debugPrintable \
  eventlog \
  files \
  frame \
  framePieces \
  frame_format \
  frame_iterator \
  hprofiler \
  init \
  interruptedCtx \
  lprintf \
  machineCache \
  monitor \
  monitorHooks \
  monitorPieces \
  nlrSupport \
  nprofiler \
  nprofiler.copygraph \
  print \
  process \
  recompile \
  registerLocator \
  runtime \
  selfMonitor \
  shell \
  stack \
  table \
  uncommonBranch \
  util \
  vframe \
         
include        ${ROOT}/templates/sources.make
