# Sun-$Revision: 1.2 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.
 
# Makefile for the Self lookup system

ROOT         = ../../../..
FILES        = Makefile \
               cacheStub_inline_i386.hh \
               cacheStub_i386.cpp \
               cacheStub_i386.hh \
               diDesc_i386.cpp \
               diDesc_i386.hh \
               sendDesc_i386.cpp \
               sendDesc_i386.hh \

         
include        ${ROOT}/templates/sources.make
