# Sun-$Revision: 30.9 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the Self runtime system

ROOT         = ../../../..

FILES =  Makefile \
         os_includes.hh \
         signalBlocker.hh \


C_MODULES =  \
  errorCodes \
  itimer \
  monitorWindow \
  os \
  platformWindow \
  sig \
  timer \
	quartzWindow \
  xlibWindow \
       
include        ${ROOT}/templates/sources.make
