# Sun-$Revision: 1.2 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.
 
# Makefile for the fast Self compiler

ROOT         = ../../../..
FILES        = Makefile \
               fcompiler_i386.hh \
               fcompiler_i386.cpp \
               codeGen_inline_i386.hh \
               codeGen_i386.cpp \
               codeGen_i386.hh \
               registerState_i386.hh \
               registerState_i386.cpp \
               registerString_i386.hh \
               registerString_i386.cpp \


include        ${ROOT}/templates/sources.make
