# Sun-$Revision: 30.6 $
 
# Copyright 1995-2006 Sun Microsystems, Inc.
# See the LICENSE file for license information.
 
# Makefile for Smalltalk

ROOT         = ../../..
FILES        = Makefile smalltalk.grm
SELF_MODULES = bootstrapClasses smalltalk smalltalkEmulator \
	       smalltalkSupport smalltalkUI smalltalk_behavior \
	       generated_by_smalltalk
DIRECTORIES  = smalltalkSrc

include        ${ROOT}/templates/sources.make
