# Sun-$Revision: 30.7 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the Self memory system

ROOT         = ../../../..
FILES        = Makefile spaceSizeMacros.hh

C_MODULES    = ageTable \
               asmErrorCodes \
               enumeration \
               generation \
               mapTable \
               mapVtbls \
               oopClosures \
               oTable \
               rSet \
               search \
               slotIterator \
               slotList \
               space \
               spaceSize \
               stringTable \
               universe \
               universe.more \
               vmStrings \
       
include        ${ROOT}/templates/sources.make


