# Sun-$Revision: 30.7 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the Self assembler
ROOT         = ../../..
FILES        = Makefile

DIRECTORIES = asm \
        fast_compiler \
        interpreter \
        lookup \
        memory \
        objects \
        os \
        parser \
        prims \
        runtime \
        sic \
        zone

include        ${ROOT}/templates/sources.make
