#
# Sun-$Revision: 30.6 $ $UW-Revision$
#
# Makefile for the SIC Self compiler
#

ROOT         = ../../../..
FILES        = Makefile \
               basicNode_ppc.hh \
               deadBlockNode_ppc.hh \
               deadBlockNode_ppc.cpp \
               genHelper_ppc.hh \
               genHelper_ppc.cpp \
               longRegString_ppc.hh \
               longRegString_ppc.cpp \
               node_ppc.cpp \
               prologueNode_ppc.hh \
               sic_ppc.hh \
               sic_ppc.cpp

include        ${ROOT}/templates/sources.make
