# Sun-$Revision: 30.13 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the Self primitives

ROOT         = ../../../..

FILES        = Makefile
               
C_MODULES    = dynLink \
               glue \
               glueCheckSum \
               glueDefs \
               glueSupport \
               include_glue \
               miscPrims \
               prim \
               prim_table_arch \
               prim_table_os \
               prim_table_quartz \
	       quartzPrims
       
include        ${ROOT}/templates/sources.make
