# Sun-$Revision: 30.7 $

# Copyright 1994-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.

ROOT         = ../..
FILES        = Makefile
DIRECTORIES  = \
	asmKit \
        avExtensions \
        javaClient \
        javaServer \
        klein \
        mango \
        parseKit \
        pep \
        preprocessor \
        serverDemo \
        smalltalk \
        sorting \
        webBrowser \
	      selfParser \
        sliceOutliner \

include        ${ROOT}/templates/sources.make
