# Sun-$Revision: 30.7 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.
 
# Makefile for the fast Self compiler

ROOT         = ../../../..
FILES        = Makefile \
               fcompiler_ppc.hh \
               fcompiler_ppc.cpp \
               codeGen_inline_ppc.hh \
               codeGen_ppc.cpp \
               codeGen_ppc.hh \
               registerState_ppc.hh \
               registerState_ppc.cpp \
               registerString_ppc.hh \
               registerString_ppc.cpp \


include        ${ROOT}/templates/sources.make
