# Sun-$Revision: 30.9 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.
 
# Makefile for the Self assembler
ROOT         = ../../../..
FILES        = Makefile \
               asm_inline_ppc.hh \
               asm_ppc.cpp \
               asm_ppc.hh \
               disasm_ppc.cpp \
               disasm_ppc.hh \
               fields_ppc.cpp \
               fields_ppc.hh \
               regs_ppc.cpp \
               regs_ppc.hh \


include        ${ROOT}/templates/sources.make
