#
# Sun-$Revision: 30.4 $ $UW-Revision$
#
# Makefile for the SIC Self compiler
#

ROOT         = ../../../..
FILES        = Makefile

C_MODULES    = \
         deadBlockNode_sparc \
         genHelper_sparc \
         longRegString_sparc \
         node_sparc \
         sic_sparc
         
include        ${ROOT}/templates/sources.make
