#
# Sun-$Revision: 1.1 $ $UW-Revision$
#
# Makefile for the SIC Self compiler
#

ROOT         = ../../../..
FILES        = Makefile \
               basicNode_i386.hh \
               deadBlockNode_i386.hh \
               deadBlockNode_i386.cpp \
               genHelper_i386.hh \
               genHelper_i386.cpp \
               longRegString_i386.hh \
               longRegString_i386.cpp \
               node_i386.cpp \
               prologueNode_i386.hh \
               sic_i386.hh \
               sic_i386.cpp

include        ${ROOT}/templates/sources.make
