# Sun-$Revision: 30.6 $
 
# Copyright 1996-2006 Sun Microsystems, Inc.
# See the LICENSE file for license information.
 
# Makefile for the Java client

ROOT         = ../../..
FILES        = Makefile                  \
               CutoutBrowser.java        \
               LensRadarViewer.java      \
               RadarViewer.java          \
               SelfDisconnectButton.java \
               SelfViewer.java           \
               Structure.java            \
               Utils.java                \
               Viewer.java               \
               makedate                  \
               makefile.java             \
               Test.html                 \
               Simple.html               \
               README                    \
               BuildJavaClient           \
               JavaClientServerOverview.txt

include        ${ROOT}/templates/sources.make
