#!/bin/bash

mkdir self-website
cd self-website
cvs export -Dnow contrib manuals public_html tutorial
cd public_html

rm README.txt  # just a note I left there to remind us what's what
rm -r self     # old version of website; should probably take this out of CVS altogether

mv ../contrib .
cd contrib
# We store mango in CVS in unzipped form but offer it in zipped form.
tar -zcvf mango.tar.gz mango
rm -r mango
cd ..

mv ../manuals .
cd manuals
rm -r source
mv ../../tutorial/* .
rmdir ../../tutorial
# We offer the HTML version of the tutorial in both zipped form and browsable-online form.
tar -zxvf Tutorial.tar.gz 
mv Tutorial ..
cd ..
