# Sun-$Revision: 30.6 $
 
# Copyright 1995-2006 Sun Microsystems, Inc.
# See the LICENSE file for license information.
 
# Makefile for webBrowser

ROOT         = ../../..
FILES        = Makefile
SELF_MODULES = webBrowser

include        ${ROOT}/templates/sources.make
