# Sun-$Revision: 30.4 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.

ROOT         = ..
FILES        = Makefile sources.make
include        ${ROOT}/templates/sources.make
