# Sun-$Revision: 30.4 $
 
# Copyright 1994-2003 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.

ROOT         = ..
FILES        = Makefile sources.make
include        ${ROOT}/templates/sources.make
