# Sun-$Revision: 30.7 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.

ROOT         = ../..
FILES        = Makefile
SELF_MODULES = abstract_OS  \
               abstractSyntax activationText allCore all_OS annotator \
	       annotation barrier\
               beamIn beamOut bigInt block boolean bootstrapFile \
	       bufferedBootstrapFile \
	       browsing bytecodeFormat\
               caseStatement chain \
	       collection collector coreObjects debugger\
               defaultBehavior defaultPreferences diff \
               enumerating errorHandling\
	       fakeSlot \
	       fakeSlotsIterator \
               fastTransporter \
               fileOut \
	       fileStream \
	       float foreign generatedCases history\
	       incrementalSaving \
	       int32and64 \
               hosts indexable init inspect integer interceptor \
               list lock \
	       macOS macOS_stdin \
               metaCollections \
               message\
               memoryState methodText mirror module moduleInfo monitor \
	       nil number objectScanner\
	       oldStyleRectangle orderedDictionary orderedSet \
	       pair path ping point primitives\
               priorityQueue process processErrors processStack\
               processStatus processesAndIO profiler profiling programmingLog\
               programmingSupport prompt random rectangle rootTraits\
               scheduler selectionText selector semaphore sending sequence\
               serializer setAndDictionary sharedQueue sharedSetAndDictionary\
               shell shortcuts slot smallInt snapshotAction socketServer \
	       sortedSequence\
               stat stdin string systemOddballs systemStructure\
               termcap textLines time transporter transporterFiles tree tty \
               ttySupport unix unix_stdin vector visibility
include        ${ROOT}/templates/sources.make
