# Sun-$Revision: 30.7 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the Self primitives

ROOT         = ../../../..

FILES        = Makefile \
         asmPrims_sparc.s \
         memCopyPrims_sparc.s \
         prim_table_arch_sparc.hh \
         
               
         
include        ${ROOT}/templates/sources.make
