#!/bin/sh

# Sun-$Revision: 30.3 $

# Copyright 1992-2001 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information. 

# User setup script for the Self system

cat <<EOM

This script will check if your work station is fit to run Self.

EOM

if test `uname -r` -ge 5.0; then
  PATH=/usr/ucb:$PATH
  dmesg=/usr/sbin/dmesg
  subdir=svr4
else
  dmesg=/usr/etc/dmesg
  subdir=sun4
fi

awk=/usr/bin/awk

#---------------- Functions

# need <program>
#  exit if program is absent.
need()
{
  if test ! -x $1; then
    echo "Sorry, you need to have $1 to run the setup script."
    echo "Setup aborted."
    exit 1
  fi
}

need $awk

#---------------- Variables
physmem=0
virtmem=0
maxselfmem=0

#---------------- Defaults
defaultPhysMem=16
defaultVirtMem=0

echo "Checking your machine configuration..."

if sparc; then
    echo " - Great, your machine has a Sparc processor."
else
    echo "Sorry, you need a Sparc to run Self"
    exit 1
fi

# try to determine physmem
if test -x $dmesg; then
   if $dmesg | grep 'avail mem ' >/dev/null 2>&1 ; then
      physmem=`$dmesg|grep 'avail mem '|tail -1 | $awk ' { print int($4 / 1024 /1024) }'`
   fi
fi

echo " - Your system has at least $physmem Mbytes of real memory."

# try to determine virtmem
set virtmem = 0

if test `uname -r` -ge 5.0; then
  pp=/usr/sbin/swap
  if test -x $pp; then
    virtmem=`$pp -s | $awk '{ print int(substr($11, 0, length($11)-1) / 1024)}'`
  fi
else
  pp=/usr/etc/pstat
  if test -x $pp; then
    virtmem=`$pp -s | $awk '{ print int(substr($9, 0, length($9)-1) / 1024)}'`
  fi
fi

echo " - Your system has $virtmem Mbytes of virtual memory."

maxselfmem=`expr $physmem - 8`

home=$HOME

old=10; code=4.0; ui=3;

echo "Computing memory requirements..."
vm=4.5		# VM code + C heap + resource area
eden=0.4
surv=0.3

totalV=`echo "$vm + $eden + 2*$surv + 1.05*$old + 2.7*$code + $ui" | bc`
totalR=`echo "$vm + $eden +   $surv +      $old + 1.7*$code + $ui" | bc`

echo " - This configuration needs $totalV Mbytes of virtual memory"
echo " - and $totalR Mbytes of real memory"
echo


#---------------- Is there enough memory
extraV=`echo $virtmem - $totalV | bc`
extraR=`echo $physmem - $totalR | bc`

case "$extraV" in
  -*)
    echo "Your machine does not have enough virtual memory to run Self as specified"
    echo "An additional" `echo "0 - $extraV"| bc` "Mbytes of virtual memory are"
    echo "needed.  Please choose a smaller configuration or tell your system"
    echo "administrator to increase this machine's swap space."
    exit 1
    ;;
esac

case "$extraR" in
  -*)
    echo "Warning: Your system does not have enough real memory to run Self well."
    echo "The system may page excessively when you run Self, but it might still"
    echo "work. An additional" `echo "0 - $extraR"| bc` "Mbytes of real are needed"
    echo "required for good system performance."
    echo
    ;;
  *)
   echo "It appears that you have enough memory to run Self 3.0 well."
   echo "In fact, you have about" $extraR "MB of real memory to spare."
   echo
   ;;
esac

unknownLibs()
{
  result=`ldd Self |\
          grep "not found" |\
          $awk '{ printf(" %s", $1) }`
}

echo "Checking if Self can load the shared libraries..."
unknownLibs

if test "$result" != ""; then
  echo " - The environment variable LD_LIBRARY_PATH must be extended"
  echo "   since the shared libaries $result could not be found. "
  echo "   Ask your system administrator where these libraries can be found."
  echo
fi

echo "CheckInstall done."
echo
echo "Type:"
echo "   ./Snapshot"
echo "to start the Self system."
echo
