#! /bin/sh

# Sun-$Revision: 30.3 $

# Copyright 1995-2001 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information. 

# Installation script for the Self system.
# Unpack Self-4.0.tar.{Z,gz} in current directory.

#-------------

usage ()
{
	echo $0: usage: $0 Self-archive-file-name
	echo
	echo Possible archive file names are:
	echo   Self-4.0.sunos.tar.Z Self-4.0.sunos.tar.gz
	echo   Self-4.0.solaris.tar.Z Self-4.0.solaris.tar.gz
	exit 1
}

if [ $# -ne 1 ]
then
  usage
fi

case $1 in
 Self-4.0.sunos.tar.gz) ;;
 Self-4.0.sunos.tar.Z) ;;
 Self-4.0.solaris.tar.gz) ;;
 Self-4.0.solaris.tar.Z) break ;;
 *) usage;;
esac

SelfFile=$1

#-------------

PATH=/usr/ucb:/usr/bin:/usr/sbin:$PATH
export PATH

cat <<EOM

This installation script creates a subdirectory called "self"
and installs the self files there.  It will also create subdirectories
called "alchemy" and "pbmplus" for utilities required by the Self Web
browser.

EOM

echo -n "Please press Return to continue the installation... "
read ans

if test	-f $SelfFile; then
  echo "Installing $SelfFile"
else
  echo "Couldn't find a compressed tar file to install."
  echo "(Expected to find $SelfFile.)"
  echo "Installation aborted."
  exit 1
fi

echo

if test -d ./self; then
  echo "The directory ./self already exists. Do you want to install the "
  echo -n "new files in the already existing directory [n]? "
  read ans
  case "$ans" in
    "y"|"yes")
      ;;
    *)
      echo "Installation aborted."
      exit 1
      ;;
  esac
fi

unpack()
{
  echo
  echo -n "Unpacking the Self system from $1..."
  case $1 in
  *.Z) zcat ;;
  *.gz) gunzip ;;
  esac <$1 | tar -xfpB -
  echo " done."
}

unpack $SelfFile

echo
echo "Installation done."

exit 0
