# Sun-$Revision: 30.3 $

# Copyright 1992-2001 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.

# Makefile for the Self ftp information

ROOT         = ..
FILES        = Makefile \
	       LICENSE \
	       AlphaInfo \
	       README.top \
	       README.manuals \
	       README.system \
	       vmUseDoc \
               Install \
               CheckInstall
include        ${ROOT}/templates/sources.make
