# Sun-$Revision: 30.9 $
 
# Copyright 1995-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the Self interpreter

ROOT         = ../../../..
FILES        = Makefile
C_MODULES    = abstract_interpreter \
               interpreter \
               stacking_interpreter

include        ${ROOT}/templates/sources.make
