# Sun-$Revision: 30.6 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.

ROOT         = ../..
FILES        = Makefile
SELF_MODULES = allTests tests programmingTests branchTests \
	       debugTests lowLevelTests\
               numberTests sicTests deltablue cons benchmarks richards\
               parser parseNodes
include        ${ROOT}/templates/sources.make
