# Sun-$Revision: 30.6 $

# Copyright 1994-2006 Sun Microsystems, Inc.
# See the LICENSE file for license information.

ROOT         = ../../..
FILES        = Makefile
DIRECTORIES = tests
SELF_MODULES = \
	       selfLexer \
	       selfLexerTokens \
	       selfMinis \
	       selfParseNodes \
	       selfParser \
	       selfParserTester \

include        ${ROOT}/templates/sources.make
