# generated by /Users/tobias/dev/self/self/vm/mac_osx/vm_project/../../..//bin/shell/make_vmDate -- do not change by hand 
.const
.globl _vmDate 
LC0: 
.asciz  "Thu 10 May 12 15:53:25 Mac OSX I386"
.align 4 
_vmDate: .long LC0
