# Sun-$Revision: 30.7 $
 
# Copyright 1992-2012 AUTHORS.
# See the LICENSE file for license information.
 
# Makefile for the Self lookup system

ROOT         = ../../../..
FILES        = Makefile \
               cacheStub_inline_ppc.hh \
               cacheStub_ppc.cpp \
               cacheStub_ppc.hh \
               diDesc_ppc.cpp \
               diDesc_ppc.hh \
               sendDesc_ppc.cpp \
               sendDesc_ppc.hh \

         
include        ${ROOT}/templates/sources.make
