# Sun-$Revision: 1.1 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the Self linux optimized object directory

ROOT         = ../../..
FILES        = Makefile
AOUT         = Self
UPDATE_EXCL  = ${AOUT}

include        ${ROOT}/vm/templates/linux.make
include        ${ROOT}/vm/templates/optimized.make
include        ${ROOT}/templates/sources.make
include        ../generated/Dependencies
