# Sun-$Revision: 30.8 $
 
# Copyright 1992-2006 Sun Microsystems, Inc. and Stanford University.
# See the LICENSE file for license information.
 
# Makefile for the Self runtime system

ROOT         = ../../../..
FILES        = Makefile \
               os_includes_unix.hh \

C_MODULES    = \
         errorCodes_unix \
               itimer_unix \
               os_unix \
               sig_unix \
               signalBlocker_unix \
               timer_unix \
         
include        ${ROOT}/templates/sources.make
