# Sun-$Revision: 30.6 $
 
# Copyright 1995-2006 Sun Microsystems, Inc.
# See the LICENSE file for license information.
 
# Makefile for Smalltalk sources

ROOT         = ../../../..
FILES        = Makefile Array.st ArrayedCollection.st \
	ArrayedCollection2.st Association.st Bag.st ByteArray.st Character.st \
	Character2.st Collection.st Collection2.st Date.st Dictionary.st \
	IdentityDictionary.st Interval.st Link.st LinkedList.st LookupKey.st \
	Magnitude.st MappedCollection.st Message.st Object.st Object2.st OrderedCollection.st \
	PositionableStream.st ReadStream.st ReadWriteStream.st STones80.st \
	SequenceableCollection.st SequenceableCollection2.st Set.st SortedCollection.st Stream.st \
	String.st Symbol.st SystemDictionary.st Time.st TranscriptObj.st \
	UndefinedObject.st UndefinedObject2.st WriteStream.st \
	deltaBlue.st diff.st richards.st Smalltalk_copying_policy README 

include        ${ROOT}/templates/sources.make
