#
# Sun-$Revision: 9.1 $
# Copyright 1992:
#   The Cecil Group: Craig Chambers, Claudia Chiang, and Stuart Williams
#   University of Washington, Seattle, WA
#
# Makefile for the Cecil interpreter Self code
#

default:
	@echo 'no default target'

ROOTDIR	= ../../..

RCS_FILES    = Makefile

RCS_SUFFIXES = .self
RCS_NAMES    = \
	cecil-ui \
	cecilArgEntry \
	cecilArrow \
	cecilBoxLayout \
	cecilColormap \
	cecilColors \
	cecilFieldArrow \
	cecilFieldEntry \
	cecilFieldsPane \
	cecilFullBox \
	cecilIconBox \
	cecilMethodArrow \
	cecilMethodBodyEntry \
	cecilMethodBodyPane \
	cecilMethodBox \
	cecilMethodEntry \
	cecilMethodsPane \
	cecilMenu \
	cecilObjectBox \
	cecilObjectPane \
	cecilPaneEntry \
	cecilParentArrow \
	cecilParentEntry \
	cecilParentsPane \
	cecilResultEntry \
	cecilUI \
	cecilUIBox \
	cecilUIController \
	cecilUIMovingBox \
	cecilUITempBox


FTP_VM_FILES    = ${RCS_FILES}
FTP_VM_SUFFIXES = ${RCS_SUFFIXES}
FTP_VM_NAMES    = ${RCS_NAMES}

include ${ROOTDIR}/MakefileSrcTemplate
include ${ROOTDIR}/MakefileFTPTemplate
include ${ROOTDIR}/MakefilePublishTemplate


